# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Simple GDPR Cookie Banner"
client_id = "365a12267a47dc9b4591f27cd6edf2bb"
application_url = "https://shopify-gdpr-banner-app.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shopify-gdpr-banner-app.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "demo-store-gorilla-monk.myshopify.com"
